name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
api-version: '1.20'
depends: [ 'NBTApi' ]
authors: [ CuzIm1Tigaaa ]
description: 'TODO'
commands:
  smartsaddle:
    description: 'Reload the config files'
permissions:
  smartsaddle.*:
    default: op
    children:
      smartsaddle.use:
        default: false
        children:
          smartsaddle.use.horse:
            default: false
          smartsaddle.use.skeleton_horse:
            default: false
          smartsaddle.use.zombie_horse:
            default: false
          smartsaddle.use.donkey:
            default: false
          smartsaddle.use.mule:
            default: false
          smartsaddle.use.camel:
            default: false